// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	model "challenge.haraj.com.sa/kraicklist/model"
	mock "github.com/stretchr/testify/mock"
)

// Filesearch is an autogenerated mock type for the Filesearch type
type Filesearch struct {
	mock.Mock
}

// Load provides a mock function with given fields:
func (_m *Filesearch) Load() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: query
func (_m *Filesearch) Search(query string) ([]model.Record, error) {
	ret := _m.Called(query)

	var r0 []model.Record
	if rf, ok := ret.Get(0).(func(string) []model.Record); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Record)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
