// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	wrapper "challenge.haraj.com.sa/kraicklist/pkg/wrapper"
)

// HomeUsecase is an autogenerated mock type for the HomeUsecase type
type HomeUsecase struct {
	mock.Mock
}

// SearchFromFile provides a mock function with given fields: ctx, whatToSearch
func (_m *HomeUsecase) SearchFromFile(ctx context.Context, whatToSearch string) wrapper.Result {
	ret := _m.Called(ctx, whatToSearch)

	var r0 wrapper.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) wrapper.Result); ok {
		r0 = rf(ctx, whatToSearch)
	} else {
		r0 = ret.Get(0).(wrapper.Result)
	}

	return r0
}
