// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "challenge.haraj.com.sa/kraicklist/model"
)

// HomeRepo is an autogenerated mock type for the HomeRepo type
type HomeRepo struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, stringToSearch
func (_m *HomeRepo) Search(ctx context.Context, stringToSearch string) ([]model.Record, error) {
	ret := _m.Called(ctx, stringToSearch)

	var r0 []model.Record
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Record); ok {
		r0 = rf(ctx, stringToSearch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Record)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stringToSearch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
